import type { Metadata } from "next";
import "./globals.css";
import JotaiProvider from "./providers/JotaiProvider";
import '@fortawesome/fontawesome-free/css/all.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <JotaiProvider>
          {children}
        </JotaiProvider>
      </body>
    </html>
  );
}
